#include <vzor/vzor.h>

namespace Vzor
{
	namespace Database
	{
		// REFLECTED ARRAY DEFINITION HERE

		struct TypeRegistrator
		{
			TypeRegistrator(ReflectedType&& type)
			{
				std::memcpy(&AllReflectedTypes[type.TypeId], &type, sizeof(ReflectedType));
			}
		};

		static struct ReflectedDatabaseInitializer
		{
			ReflectedDatabaseInitializer()
			{
				Vzor::Detail::AllReflectedTypes = AllReflectedTypes;
			}
		} VzorInitializer;

		// Do not modify this file beyond this point - it is autogenerated
		// REFLECTED DATA BEGINS HERE

		// REFLECTED DATA ENDS HERE
	}
}